[package]
name = "flocking"
version = "0.1.0"
authors = ["grouter"]
edition = "2018"

[dependencies]
glium = "*"
cgmath = "0.18.0"
vecmath = "1.0.0"
rand = "0.8.3"
crossbeam = "0.8"
hashbrown = "0.11.2"
rayon = "1.5.1"
itertools = "0.10.0"

[profile.release]
debug = 1